[package]

name = "compiler_mir"
version = "0.0.1"
authors = ["Dylan McKay <dylanmckay34@gmail.com"]

[dependencies.compiler_ir]
path = "../ir"
[dependencies.compiler_util]
path = "../util"

[dependencies]
num = "*"

[lib]
name = "compiler_mir"
path = "lib.rs"
