[package]

name = "compiler_regalloc"
version = "0.0.1"
authors = ["Dylan McKay <dylanmckay34@gmail.com"]

[dependencies.compiler_util]
path = "../util"

[lib]
name = "compiler_regalloc"
path = "lib.rs"

