[package]

name = "compiler_pass"
version = "0.0.1"
authors = ["Dylan McKay <dylanmckay34@gmail.com"]

[dependencies]
num = "*"

[dependencies.compiler_ir]
path = "../ir"

[lib]
name = "compiler_pass"
path = "lib.rs"

